### PR TITLE
Convert to .netstandard2.0

### PR DESCRIPTION
**Pull request by buvinghausen**

### CODE REVIEW

**Comment by buvinghausen** [comment]
as long as you have the dotnet cli 2.0 installed the steps you need to take are

cd src
dotnet restore
dotnet build -c Release
dotnet test

I have the build step automatically emitting the nupkg file you can of course tease that apart and make it a separate step if you like with dotnet pack -c Release.

Here's the output from dotnet test
image

**Comment by jakubka** [comment]
Hey @buvinghausen,

Thanks for this big contribution!

The code looks good to me.

This will however drop support for the 'classic' .NET Framework unless I am mistaken?

I don't think this is desirable? Shouldn't we release the package under different name to keep the compatibility with both frameworks?

To be honest, I am not living in .NET world for a while now, so I am not sure how is it normally handled.

Cheers

**Comment by buvinghausen** [comment]
@jakubka I went ahead and made a new nuget.org package which I will maintain going forward. I've just called it Swashbuckle.NodaTime.AspNetCore let me know if you want me to change/fix any of the attributions to your initial works. I am going to go ahead and close this PR now as you don't need to worry about it.  Thanks for your help!

**Comment by jakubka** [comment]
Thanks @buvinghausen !

**Pull request closed without merging**
